import { REALTIME_EVENTS } from "@/lib/realtime/events";

export const BOARD_CALENDAR_INVALIDATE_EVENTS = [
  REALTIME_EVENTS.CARD_CREATED,
  REALTIME_EVENTS.CARD_UPDATED,
  REALTIME_EVENTS.CARD_DELETED,
  REALTIME_EVENTS.CARD_MOVED,
  REALTIME_EVENTS.CARD_REORDERED,
  REALTIME_EVENTS.CARD_COMMENT_COUNT_UPDATED,
  REALTIME_EVENTS.CARD_MEMBER_ASSIGNED,
  REALTIME_EVENTS.CARD_MEMBER_UNASSIGNED,
  REALTIME_EVENTS.CARD_LABEL_ATTACHED,
  REALTIME_EVENTS.CARD_LABEL_DETACHED,
  REALTIME_EVENTS.LABEL_UPDATED,
  REALTIME_EVENTS.LABEL_DELETED,
  REALTIME_EVENTS.CHECKLIST_UPDATED,
  REALTIME_EVENTS.CHECKLIST_DELETED,
  REALTIME_EVENTS.CHECKLIST_ITEM_CREATED,
  REALTIME_EVENTS.CHECKLIST_ITEM_UPDATED,
  REALTIME_EVENTS.CHECKLIST_ITEM_DELETED,
  REALTIME_EVENTS.CHECKLIST_ITEM_TOGGLED,
  REALTIME_EVENTS.CHECKLIST_ITEM_ASSIGNEE_UPDATED,
  REALTIME_EVENTS.CHECKLIST_ITEM_DUE_DATE_UPDATED,
  REALTIME_EVENTS.CHECKLIST_ITEM_REORDERED,
  REALTIME_EVENTS.CHECKLIST_ITEM_MOVED,
] as const;

export const BOARD_CALENDAR_REFRESH_EVENTS = [
  REALTIME_EVENTS.BOARD_MEMBER_ADDED,
  REALTIME_EVENTS.BOARD_MEMBER_ROLE_UPDATED,
  REALTIME_EVENTS.LIST_CREATED,
  REALTIME_EVENTS.LIST_UPDATED,
  REALTIME_EVENTS.LIST_DELETED,
  REALTIME_EVENTS.LIST_REORDERED,
] as const;

export const BOARD_CALENDAR_ACCESS_REVOKE_EVENTS = [
  REALTIME_EVENTS.BOARD_ACCESS_REVOKED,
  REALTIME_EVENTS.BOARD_MEMBER_REMOVED,
] as const;

export const BOARD_CALENDAR_DELETE_EVENTS = [
  REALTIME_EVENTS.BOARD_DELETED,
] as const;
